### ISSUE TITLE
Does the docker method support streaming output?

### ISSUE THREAD

**Issue by mufeng510** [ramonvc/freegpt-webui#66]
this is my docker compose:
```
freegpt:
    image: ramonvc/freegpt-webui
    container_name: freegpt
    network_mode: host
    restart: always
    environment:
      - HTTP_PROXY=http://127.0.0.1:20171
      - HTTPS_PROXY=http://127.0.0.1:20171
```
I used v2ray as proxy，no nginx. 
Can't get the typewriter effect right now
